In [ ]:
#TESTES COM REDES NEURAIS

In [ ]:
# vamos fazer alguns testes variando número e densidade de camadas assim como qual matriz de ativação utilizamos e veremos
# como isso influencia a acurácia da nossa rede neural

In [ ]:
#redes neurais artificiais
#deep learning usando o python
#vamos importar os dados de tipo de vinho, branco e tinto
#vamos importar direto do site, muito legal

In [1]:
import pandas as pd
white=pd.read_csv("http://archive.ics.uci.edu/ml/machine-learning-databases/wine-quality/winequality-white.csv",sep=';')
red=pd.read_csv("http://archive.ics.uci.edu/ml/machine-learning-databases/wine-quality/winequality-red.csv",sep=';')
from sklearn.model_selection import train_test_split

In [ ]:
#vamos criar a variável que vai separar identificar se o vinho é branco ou tinto

In [2]:
red['type']=1
white['type']=0

In [ ]:
#agora vamos juntar as duas bases de dados

In [3]:
wines=red.append(white,ignore_index=True)
X=wines.iloc[:,0:11]
import numpy as np
y=np.ravel(wines.type)

In [ ]:
#agora vamos separar as bases de dados entre treino e teste

In [4]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.33,random_state=42)

In [ ]:
#agora vamos padronizar os dados (seus valores variam entre os observados em uma distribuição normal)

In [5]:
from sklearn.preprocessing import StandardScaler
scaler=StandardScaler().fit(X_train)
X_train=scaler.transform(X_train)
X_test=scaler.transform(X_test)

In [ ]:
#vamos agora fazer o modelo
#vamos utilizar a matriz de ativação relu, que é a mais comumenten utilizada
#vamos utilizar Sequential() para passar um conjunto de camadas para nossa rede neural
#para determinar as camadas que vamos ter no modelo configuramos os
#parâmetros input_shape,input_dim,input_length ou batch_size
#por meio da função Dense, determinamos cada layer

In [7]:
from keras.models import Sequential
from keras.layers import Dense

In [ ]:
#vamos determinar nossa primeira camada (input): dimensão 12 
#vamos determinar nossa segunda camada (intermediate layer): dimensão 8 
#vamos determinar nossa terceira camada (output): dimensão 1

In [ ]:
#como vemos, há duas decisões que devem ser tomadas, quantas camadas um modelo
#deve ter e o quão densa cada camada deve ser (no nosso caso temos 3 camadas
#cada uma com densidade de, respectivamente 12, 8 e 1)
#é padrão utilizar como dimensão da camada input (primeira) a dimensão do nosso
#dataset (11 variáveis independentes 1 dependente, para não dar overfitting) e como #output (obvio dimensão 1 pois é a nossa variável dependente)
#agora vamos compilar o modelo. Vamos utilizar o otimizador adam (mas há outros)
#como estamos tentando prever um valor binário, vamos utilizar o loss=binar_crossentropy
#mas se estivessemos tentando prever um valor mult-class, deveríamos utilizar
#categorical_crossentropy (fazendo uma analogia, é semelhante ao valor minimizado
#quanto utilizamos regressão, que é o Mean Squared Error (MSE))

In [ ]:
# IMPORTANTÍSSIMO: LEMBRAR QUE PARA REDES NEURAIS QUE PREVEEM VARIÁVEIS DUMMY, A CAMADA DE OUTPUT TAMBÉM TEM QUE APRESENTAR
# UMA MATRIZ DE ATIVAÇÃO, NESSE CASO 'sigmoid'. CASO CONTRÁRIO, OS VALORES PREVISTOS NÃO SERIAM APENAS 0 OU 1

In [8]:
model=Sequential()
model.add(Dense(12,activation='relu',input_shape=(11,)))
model.add(Dense(8,activation='relu'))
model.add(Dense(1,activation='sigmoid'))
model.compile(loss='binary_crossentropy',optimizer='adam',metrics=['accuracy'])

In [ ]:
#vamos treinar o modelo com 20 epochs, ou iterações sobre a amostra em X_train e ytrain
#epochs=20 indica que o modelo será treinado passando 20 vezes por toda a base de treino
#batch_size identifica o número de amostras a serem propagadas pela rede (uma só pois
#só estamos utilizando uma base de dados)
#o argumento verbose=1 indica que queremos ver em tela as iterações do modelo

In [9]:
model.fit(X_train,y_train,epochs=20,batch_size=1,verbose=1)
y_pred=model.predict(X_test)

Epoch 1/20
4352/4352 [==============================] - 36s 1ms/step - loss: 0.1492 - accuracy: 0.9473
Epoch 2/20
4352/4352 [==============================] - 5s 1ms/step - loss: 0.0219 - accuracy: 0.9966: 0s
Epoch 3/20
4352/4352 [==============================] - 5s 1ms/step - loss: 0.0140 - accuracy: 0.9978
Epoch 4/20
4352/4352 [==============================] - 5s 1ms/step - loss: 0.0155 - accuracy: 0.9971
Epoch 5/20
4352/4352 [==============================] - 5s 1ms/step - loss: 0.0143 - accuracy: 0.9975
Epoch 6/20
4352/4352 [==============================] - 5s 1ms/step - loss: 0.0168 - accuracy: 0.9961
Epoch 7/20
4352/4352 [==============================] - 5s 1ms/step - loss: 0.0134 - accuracy: 0.9976
Epoch 8/20
4352/4352 [==============================] - 5s 1ms/step - loss: 0.0157 - accuracy: 0.9974
Epoch 9/20
4352/4352 [==============================] - 5s 1ms/step - loss: 0.0167 - accuracy: 0.9968
Epoch 10/20
4352/4352 [==============================] - 5s 1ms/step - loss: 

In [ ]:
#y_pred vai nos dar a porcentagem de chance de cada vinho ser tinto

In [10]:
y_pred[:5]
y_test[:5]

array([0, 1, 0, 0, 0], dtype=int64)

In [ ]:
#agora vamos avaliar o modelo

In [11]:
score=model.evaluate(X_test,y_test,verbose=1)
print(score)
from sklearn.metrics import confusion_matrix, precision_score, recall_score, f1_score, cohen_kappa_score

68/68 [==============================] - 1s 1ms/step - loss: 0.0268 - accuracy: 0.9953
[0.026782097294926643, 0.9953380227088928]


In [ ]:
#para a matriz de confusão, vamos precisar arredondar os valores

In [16]:
y_pred=np.rint(y_pred)
confusion_matrix(y_test,y_pred)

array([[1584,    4],
       [   6,  551]], dtype=int64)

In [17]:
precision_score(y_test,y_pred)

0.9927927927927928

In [18]:
recall_score(y_test,y_pred)

0.9892280071813285

In [19]:
f1_score(y_test,y_pred)

0.9910071942446043

In [20]:
cohen_kappa_score(y_test,y_pred)

0.9878605748824258

In [ ]:
# vamos fazer alguns testes para ver se conseguimos melhorar o modelo

In [ ]:
# primeiro vamos usar meu padrão, que são três camadas, a primeira com densidade igual ao total de variáveis dependente
# e independente. A segunda com a metade da densidade e a terceira com densidade 1.

In [28]:
model2=Sequential()
model2.add(Dense(12,activation='relu',input_shape=(11,)))
model2.add(Dense(6,activation='relu'))
model2.add(Dense(1,activation='sigmoid'))
model2.compile(loss='binary_crossentropy',optimizer='adam',metrics=['accuracy'])
model2.fit(X_train,y_train,epochs=20,batch_size=1,verbose=1)
y_pred=model2.predict(X_test)

Epoch 1/20
4352/4352 [==============================] - 8s 2ms/step - loss: 0.1896 - accuracy: 0.9469
Epoch 2/20
4352/4352 [==============================] - 9s 2ms/step - loss: 0.0279 - accuracy: 0.9936
Epoch 3/20
4352/4352 [==============================] - 7s 2ms/step - loss: 0.0183 - accuracy: 0.9956
Epoch 4/20
4352/4352 [==============================] - 7s 2ms/step - loss: 0.0192 - accuracy: 0.9967: 1s - loss: 0.0 - ETA: 0s - los
Epoch 5/20
4352/4352 [==============================] - 6s 1ms/step - loss: 0.0122 - accuracy: 0.9983
Epoch 6/20
4352/4352 [==============================] - 8s 2ms/step - loss: 0.0153 - accuracy: 0.9957
Epoch 7/20
4352/4352 [==============================] - 6s 1ms/step - loss: 0.0123 - accuracy: 0.9976: 3s - loss: 0 - ETA: 0s - loss: 0.0123 - accuracy: 0. - ETA: 0s - loss: 0.0
Epoch 8/20
4352/4352 [==============================] - 7s 1ms/step - loss: 0.0087 - accuracy: 0.9988: 5s - loss: 0.0010 - accuracy: 1.00 - E - ETA: 4s - loss: 0.0059 - accu - ET

In [29]:
score=model2.evaluate(X_test,y_test,verbose=1)
print(score)

68/68 [==============================] - 0s 1ms/step - loss: 0.0224 - accuracy: 0.9949
[0.022439932450652122, 0.9948717951774597]


In [30]:
y_pred=np.rint(y_pred)
confusion_matrix(y_test,y_pred)

array([[1585,    3],
       [   8,  549]], dtype=int64)

In [ ]:
# Não variou consideravelmente, mas piorou um pouco acurácia