In [ ]:
## REDES NEURAIS ARTIFICIAIS

In [ ]:
#redes neurais artificiais
#deep learning usando o python
#vamos importar os dados de tipo de vinho, branco e tinto
#vamos importar direto do site, muito legal

In [1]:
import pandas as pd
import sklearn
padrao=pd.read_excel("C:/Users/Usuário/Desktop/base_final0_dummy.xlsx", engine='openpyxl')
desligados=pd.read_excel("C:/Users/Usuário/Desktop/base_final1_dummy.xlsx", engine='openpyxl')
teste=pd.read_excel("C:/Users/Usuário/Desktop/Base SA _ para ser prevista_dummy.xlsx", engine='openpyxl')

In [2]:
# a linha abaixo só funciona se eu tiver instalado o numpy pip versão 1.16.4
# ou seja, garanta que você já rodou no prompt de comando o seguinte código: pip install numpy==1.16.4
from sklearn.model_selection import train_test_split

In [ ]:
#vamos criar a variável que vai separar identificar se o vinho é branco ou tinto

In [3]:
desligados['Desligados']=1
padrao['Desligados']=0

In [ ]:
#agora vamos juntar as duas bases de dados, lembrando de separar entre as variáveis as independentes e dependentes
#sendo que as primeiras 16 são as independentes e a última que eu criei, "Desligados" é a dependente

In [4]:
base=desligados.append(padrao,ignore_index=True)
X=base.iloc[:,0:8]
import numpy as np
y=np.ravel(base.Desligados)

In [ ]:
#agora eunão vou separar entre treino e teste, vou pegar a base que estou usando como treino e pegar a base de SA como teste

In [5]:
#X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.33,random_state=42)
X_train=X
y_train=y
X_test=teste.iloc[:,0:8]
y_test=np.ravel(teste.Desligados)

In [6]:
X_train.head()

ID  BASF Tenure  BASF Job Grade  Ordem age range  Ordem Tenure  Male  \
0  37011502           17             5.2                7             6     0   
1  37023641            8             5.1                7             4     1   
2  37025878            8             5.2                7             4     1   
3  37028083            7             4.1                6             4     1   
4  37007063           14             6.1                6             5     0   

   Brasil  Lider  
0       0      1  
1       0      1  
2       1      1  
3       0      0  
4       1      1

In [7]:
y_train

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,

In [8]:
X_test.head()

ID  BASF Tenure  BASF Job Grade  Ordem age range  Ordem Tenure  Male  \
0  37001986           27             6.2                9             7     1   
1  37003084           23             5.2                8             7     1   
2  37003442           22             5.2                7             7     1   
3  37004178           21             6.2                8             7     1   
4  37005391           20             5.2                7             6     0   

   Brasil  Lider  
0       1      1  
1       1      1  
2       1      1  
3       1      1  
4       1      1

In [9]:
y_test

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
      dtype=int64)

In [6]:
#no comando abaixo iríamos padronizar as variáveis (tive que deletar todos osmissing, ou seja, perdemos umas 2 observações)

In [10]:
from sklearn.preprocessing import StandardScaler
scaler=StandardScaler().fit(X_train)
X_train=scaler.transform(X_train)
X_test=scaler.transform(X_test)

In [ ]:
#vamos agora fazer o modelo
#vamos utilizar a matriz de ativação relu, que é a mais comumenten utilizada
#vamos utilizar Sequential() para passar um conjunto de camadas para nossa rede neural
#para determinar as camadas que vamos ter no modelo configuramos os
#parâmetros input_shape,input_dim,input_length ou batch_size
#por meio da função Dense, determinamos cada layer

In [11]:
from keras.models import Sequential
from keras.layers import Dense
model=Sequential()

In [ ]:
#vamos determinar nossa primeira camada (input): dimensão 9 

In [12]:
model.add(Dense(9,activation='relu',input_shape=(8,)))

In [ ]:
#vamos determinar nossa segunda camada (intermediate layer): dimensão 7 

In [13]:
model.add(Dense(7,activation='relu'))

In [11]:
#vamos determinar nossa terceira camada (output): dimensão 1

In [14]:
model.add(Dense(1,activation='sigmoid'))

In [ ]:
#como vemos, há duas decisões que devem ser tomadas, quantas camadas um modelo
#deve ter e o quão densa cada camada deve ser (no nosso caso temos 3 camadas
#cada uma com densidade de, respectivamente 9, 7 e 1)
#é padrão utilizar como dimensão da camada input (primeira) a dimensão do nosso
#dataset (8 variáveis independentes 1 dependente, para não dar overfitting) e como
#output (obvio dimensão 1 pois é a nossa variável dependente)
#agora vamos compilar o modelo. Vamos utilizar o otimizador adam (mas há outros).
#Como estamos tentando prever um valor binário, vamos utilizar o loss=binar_crossentropy
#mas se estivessemos tentando prever um valor mult-class, deveríamos utilizar
#categorical_crossentropy (fazendo uma analogia, é semelhante ao valor minimizado
#quanto utilizamos regressão, que é o Mean Squared Error (MSE))
#se eu baixar a biblioteca tensorflow, posso utilizar a seguinte configuração
#para fazer a previsão da variável dependente binária como um MQO faría, ou
#seja, como probabilidade: horsepower_model.compile(optimizer=tf.optimizers.Adam(learning_rate=0.1),loss='mean_absolute_error')

In [15]:
model.compile(loss='binary_crossentropy',optimizer='adam',metrics=['accuracy'])

In [ ]:
#vamos treinar o modelo com 20 epochs, ou iterações sobre a amostra em X_train e ytrain
#epochs=20 indica que o modelo será treinado passando 20 vezes por toda a base de treino
#batch_size identifica o número de amostras a serem propagadas pela rede (uma só pois
#só estamos utilizando uma base de dados)
#o argumento verbose=1 indica que queremos ver em tela as iterações do modelo

In [16]:
model.fit(X_train,y_train,epochs=20,batch_size=1,verbose=1)
y_pred=model.predict(X_test)

Epoch 1/20
346/346 [==============================] - 1s 1ms/step - loss: 0.3681 - accuracy: 0.9306
Epoch 2/20
346/346 [==============================] - 0s 965us/step - loss: 0.2754 - accuracy: 0.9335
Epoch 3/20
346/346 [==============================] - 0s 1ms/step - loss: 0.2556 - accuracy: 0.9335
Epoch 4/20
346/346 [==============================] - 0s 1ms/step - loss: 0.2452 - accuracy: 0.9335
Epoch 5/20
346/346 [==============================] - 0s 1ms/step - loss: 0.2406 - accuracy: 0.9335
Epoch 6/20
346/346 [==============================] - 0s 1ms/step - loss: 0.2337 - accuracy: 0.9335
Epoch 7/20
346/346 [==============================] - 0s 1ms/step - loss: 0.2286 - accuracy: 0.9335
Epoch 8/20
346/346 [==============================] - 0s 1ms/step - loss: 0.2243 - accuracy: 0.9335
Epoch 9/20
346/346 [==============================] - 0s 1ms/step - loss: 0.2190 - accuracy: 0.9335
Epoch 10/20
346/346 [==============================] - 0s 1ms/step - loss: 0.2133 - accuracy: 0.93

In [ ]:
#y_pred vai nos dar a previsão de cada observação, se é vinho tinto ou branco

In [17]:
y_pred[:5]

array([[0.02526468],
       [0.024721  ],
       [0.01126081],
       [0.01400596],
       [0.0200364 ]], dtype=float32)

In [19]:
y_test[:5]

array([0, 0, 0, 0, 0], dtype=int64)

In [ ]:
#agora vamos avaliar o modelo

In [23]:
score=model.evaluate(X_test,y_test,verbose=1)
print(score)
from sklearn.metrics import confusion_matrix, precision_score, recall_score, f1_score, cohen_kappa_score

4/4 [==============================] - 1s 6ms/step - loss: 0.0717 - accuracy: 1.0000
[0.07165098190307617, 1.0]


In [ ]:
#para a matriz de confusão, vamos precisar arredondar os valore

In [24]:
y_pred=np.rint(y_pred)

In [25]:
confusion_matrix(y_test,y_pred)

array([[108]])

In [26]:
precision_score(y_test,y_pred)

0.0

In [27]:
recall_score(y_test,y_pred)

0.0

In [28]:
f1_score(y_test,y_pred)

0.0

In [29]:
cohen_kappa_score(y_test,y_pred)

C:\Users\Usuário\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:350: RuntimeWarning: invalid value encountered in true_divide
  k = np.sum(w_mat * confusion) / np.sum(w_mat * expected)


nan

In [ ]:
#agora, para prever a probabilidade de pertencer à categoria 1 ao invés dos valores 0 ou 1, temos que fazer algumas mudanças

In [30]:
model=Sequential()
model.add(Dense(9,activation='relu',input_shape=(8,)))
model.add(Dense(7,activation='relu'))
model.add(Dense(1,activation='sigmoid'))
model.compile(optimizer='sgd',
              loss='binary_crossentropy',
              metrics=['accuracy'])
hist = model.fit(X_train, y_train,
          batch_size=32, epochs=100,
          validation_data=(X_test, y_test))

Epoch 1/100
11/11 [==============================] - 1s 56ms/step - loss: 0.8019 - accuracy: 0.2543 - val_loss: 0.7433 - val_accuracy: 0.4259
Epoch 2/100
11/11 [==============================] - 0s 26ms/step - loss: 0.7016 - accuracy: 0.5809 - val_loss: 0.6488 - val_accuracy: 0.7315
Epoch 3/100
11/11 [==============================] - 0s 35ms/step - loss: 0.6243 - accuracy: 0.7630 - val_loss: 0.5731 - val_accuracy: 0.9074
Epoch 4/100
11/11 [==============================] - 0s 40ms/step - loss: 0.5629 - accuracy: 0.9046 - val_loss: 0.5099 - val_accuracy: 0.9815
Epoch 5/100
11/11 [==============================] - 0s 32ms/step - loss: 0.5128 - accuracy: 0.9277 - val_loss: 0.4576 - val_accuracy: 1.0000
Epoch 6/100
11/11 [==============================] - 0s 43ms/step - loss: 0.4721 - accuracy: 0.9335 - val_loss: 0.4134 - val_accuracy: 1.0000
Epoch 7/100
11/11 [==============================] - 0s 4ms/step - loss: 0.4383 - accuracy: 0.9335 - val_loss: 0.3756 - val_accuracy: 1.0000
Epoch 8

Epoch 59/100
11/11 [==============================] - 0s 4ms/step - loss: 0.2264 - accuracy: 0.9335 - val_loss: 0.0848 - val_accuracy: 1.0000
Epoch 60/100
11/11 [==============================] - 0s 4ms/step - loss: 0.2260 - accuracy: 0.9335 - val_loss: 0.0845 - val_accuracy: 1.0000
Epoch 61/100
11/11 [==============================] - 0s 4ms/step - loss: 0.2256 - accuracy: 0.9335 - val_loss: 0.0841 - val_accuracy: 1.0000
Epoch 62/100
11/11 [==============================] - 0s 4ms/step - loss: 0.2252 - accuracy: 0.9335 - val_loss: 0.0838 - val_accuracy: 1.0000
Epoch 63/100
11/11 [==============================] - 0s 4ms/step - loss: 0.2247 - accuracy: 0.9335 - val_loss: 0.0836 - val_accuracy: 1.0000
Epoch 64/100
11/11 [==============================] - 0s 4ms/step - loss: 0.2243 - accuracy: 0.9335 - val_loss: 0.0833 - val_accuracy: 1.0000
Epoch 65/100
11/11 [==============================] - 0s 4ms/step - loss: 0.2240 - accuracy: 0.9335 - val_loss: 0.0831 - val_accuracy: 1.0000
Epoch 

In [31]:
y_pred=model.predict(X_test)

In [32]:
y_pred[:5]

array([[0.02208284],
       [0.01977476],
       [0.01535201],
       [0.02227664],
       [0.02726963]], dtype=float32)

In [33]:
y_test[:5]

array([0, 0, 0, 0, 0], dtype=int64)

In [ ]:
# vamos ver todo o nosso vetor com as probabilidades

In [34]:
y_pred

array([[0.02208284],
       [0.01977476],
       [0.01535201],
       [0.02227664],
       [0.02726963],
       [0.05112404],
       [0.05317536],
       [0.02170852],
       [0.02898329],
       [0.03033203],
       [0.07303184],
       [0.03649327],
       [0.03437996],
       [0.04670465],
       [0.03172201],
       [0.03601676],
       [0.04143384],
       [0.20334837],
       [0.02332836],
       [0.04087847],
       [0.21104515],
       [0.1521079 ],
       [0.06061158],
       [0.19146684],
       [0.1522013 ],
       [0.05742112],
       [0.08341083],
       [0.05334166],
       [0.03859714],
       [0.08526191],
       [0.1836744 ],
       [0.03860977],
       [0.08586594],
       [0.04096904],
       [0.04164261],
       [0.04096848],
       [0.03637245],
       [0.03559601],
       [0.06717771],
       [0.10553449],
       [0.04095519],
       [0.09707287],
       [0.04990366],
       [0.08750835],
       [0.11504933],
       [0.05117726],
       [0.09191868],
       [0.093